### ISSUE TITLE
indentation of multiline array, call, function, object, and var

### ISSUE THREAD

**Issue by travelbasys** [millermedeiros/esformatter#236]
I did a "survey" of some multiline constructs with the default config and found some big differences.
Sorry, this issue will become somewhat lengthy:
It would possibly be more user-friendly to have the "same" behavior out-of-the box.
What do you think?
Thank you.

PS: Well, some off these issues might be addressed by the plugin wishlist, but a casual user would not greatly welcome having to deal with plugins.

---

*Call* expressions are indented 100% ok, as I should say.

We get:
<pre>
f1(1, 2, 3);
f2(1, 2, 3
);
f3(1, 2,
  3);
f4(1, 2,
  3
);

f5(1,
  2, 3);
f6(1,
  2, 3
);
f7(1,
  2,
  3);
f8(1,
  2,
  3
);

f9(
  1, 2, 3);
f10(
  1, 2, 3
);
f11(
  1, 2,
  3);
f12(
  1, 2,
  3
);

f13(
  1,
  2, 3);
f14(
  1,
  2, 3
);
f15(
  1,
  2,
  3);
f16(
  1,
  2,
  3
);
</pre>

Array literals are very similiar, but different. In a3, a5, a9, a11, a13, a15 the final continuation line gets no indentation.
<pre>
a1 = [1, 2, 3];
a2 = [1, 2, 3
];
a3 = [1, 2,
3];
a4 = [1, 2,
  3
];

a5 = [1,
2, 3];
a6 = [1,
  2, 3
];
a7 = [1,
  2,
3];
a8 = [1,
  2,
  3
];

a9 = [
1, 2, 3];
a10 = [
  1, 2, 3
];
a11 = [
  1, 2,
3];
a12 = [
  1, 2,
  3
];

a13 = [
  1,
2, 3];
a14 = [
  1,
  2, 3
];
a15 = [
  1,
  2,
3];
a16 = [
  1,
  2,
  3
];
</pre>

*Function* declarations differ from array literals, again, in that no continuation line is indented. A few samples here:
<pre>
// more ...
function f4(p1, p2,
p3
) {
  return 0;
}
;

function f5(p1,
p2, p3) {
  return 0;
}
;
function f6(p1,
p2, p3
) {
  return 0;
}
;
function f7(p1,
p2,
p3) {
  return 0;
}
// more...
</pre>

*Var* statements without initializers are ok.
<pre>
var x1, x2, x3;

var x1, x2,
  x3;

var x1,
  x2, x3;

var x1,
  x2,
  x3;
</pre>

But *var* statements with initializers are automatically spread across several lines:
<pre>
var x1 = 1,
  x2 = 2,
  x3 = 3;
</pre>

*Object* literals, too, are automatically spread across several lines:
<pre>
obj1 = {
  x1: 1,
  x2: 2,
  x3: 3
};
</pre>

**Comment by millermedeiros** [comment]
I changed the way CallExpression is handled a little bit on #238 so it should be even better now.

the ArrayExpression should be handled by #239 (basically need to replicate what is done on CallExpression)

about `FunctionExpression` and `FunctionDeclaration` we definitely need to add the `Params` to the `indentEdges`, there is a bug for it already with a sample implementation; pull request with actual fix is highly appreciated (see #231)

`VariableDeclaration` works this way since it uses the same logic for single and multi var declarations.. it was also to simplify the configuration (`lineBreak.before.VariableName = '>=1'`). - also please create a new issue for it if you think a new setting would be important.

`ObjectExpression` is handled that way because it was the easiest way to keep the code always in the same format.. for more complex behavior we would definitely need a plugin that takes into consideration the line length and other edge cases.

**Comment by millermedeiros** [comment]
closing this since `CallExpression`, `ArrayExpression` and `FunctionExpression` was handled by other bugs; feel free to create new issue for `VariableDeclaration` behavior (if you think it should be changed). cheers.
