### ISSUE TITLE
support React JSX syntax

### ISSUE THREAD

**Issue by royriojas** [millermedeiros/esformatter#242]
Not sure where to report this issue.  I could report it on rocambole, but I would also like esformatter to use a version of rocambole that uses esprima-fb instead of esprima in order to support the `jsx` syntax

This is what I ended doing in order to make `esformatter` to tolerate the `jsx` syntax

```javascript
   // needed for grunt.file.expand
    var grunt = require('grunt');

    // use it with care, I haven't check if there
    // isn't any side effect from using proxyquire to 
    // inject esprima-fb into the esformatter
    // but this type of dependency replacement
    // seems to be very fragile... if rocambole deps change 
    // this will certainly break, same is true for esprima-fb
    // use it with care
    var proxyquire = require('proxyquire');
    var rocambole = proxyquire('rocambole', {
      'esprima': require('esprima-fb')
    });

    var esformatter = proxyquire('esformatter', {
      rocambole: rocambole
    });

    // path to your esformatter configuration
    var cfg = grunt.file.readJSON('./esformatter.json');

    // expand the files from the glob
    var files = grunt.file.expand('./frontend-app/reader/js/**/*.jsx');

    // do the actual formatting
    files.forEach(function (fIn) {
      console.log('formatting', fIn);
      var output = esformatter.format(grunt.file.read(fIn), cfg);
      grunt.file.write(fIn, output);
    });
```

As you can see it might be simple a change from `esprima` to `esprima-fb`. Maybe make the parser module a property of esformatter that way it can be injected in a cleaner way

something like

```javascript
var esformatter = require('esformatter');
esformatter.setParser(require('esprima-fb')); // if not call use regular esprima.
```
Regards

**Comment by millermedeiros** [comment]
I would accept pull requests for that! The main problem is that not all parsers will return the same LOC info for the AST nodes/tokens, which might affect the way esformatter handles the code. - I tried to [convert rocambole to use accorn](https://github.com/millermedeiros/rocambole/issues/24) and ended up giving up because of that...

**Comment by royriojas** [comment]
So in order to be sure where to do this, should I made rocambole have an option to accept a different parser (mentioning that you need to use it with care, because the issues you mentioned, so basically use it at your own risk).

Then I will also update esformatter to accept an option to set the formatter from code and from the configuration file. For example, jscs does that by setting the parser in the configuration file.

Will that work? More than happy to help with that, I would prefer it instead of using the trick I'm doing now with `proxyquire`

Regards

**Comment by millermedeiros** [comment]
@royriojas yes, you would need to update both projects. It would be great if we could set the parser in the configuration file. let me know if you have any trouble.

PS: I was going to use `esprima-fb` as the default but when I tested it the esformatter unit tests was failing because of RegExp range info (https://github.com/millermedeiros/rocambole/issues/20) - maybe they already fixed the problem.

**Comment by royriojas** [comment]
Just one more question, your master branch on the rocambole repo seems to already depend on `esprima-fb` If that is the case, maybe you just have to upgrade that dep here :)

**Comment by millermedeiros** [comment]
if the esformatter tests passes with `esprima-fb` maybe we should just keep it as the default and don't worry about the config options.

**Comment by royriojas** [comment]
Rocambole tests are passing, will try esformatter with that version. Will
let you know

Roy Ronald Riojas Montenegro

**Comment by royriojas** [comment]
So Actually, I ended writing a plugin to make esformatter to play nicely with jsx files. 

https://github.com/royriojas/esformatter-jsx-ignore

The main goal of this plugin for now is to just let esformatter to play nicely with jsx files, which is basically the use case I want to use it for. 

Sadly using esrpima-fb makes your test to break (the esformatter tests). Would be nice to also have this pull request merged and published to esformatter, that way plugins like this can also be used when especified from the configuration file or options:

https://github.com/millermedeiros/esformatter/pull/246

**Comment by millermedeiros** [comment]
@royriojas very nice plugin! would you mind adding a your plugins to the [wiki](https://github.com/millermedeiros/esformatter/wiki/Plugins)? that way we know which ones are available and what they do. thanks!

**Comment by millermedeiros** [comment]
I'm going to close this for now since the plugin was a nice approach to the problem. I would really like if esformatter was able to handle files that aren't valid JS (errors or different syntax) but since my attempt with the accorn parser did not go well we might need to wait a little bit longer for that. Maybe one day we can deprecate your plugin. Cheers

**Comment by millermedeiros** [comment]
reopening and pull request #300 should fix this.

`espree` was in fact a better option than `esprima-fb` since all the unit tests passes (`class_declaration` test fails with `esprima-fb`) and development is very active.

**Comment by millermedeiros** [comment]
I'm not planning to add JSX formatting into esformatter itself, I just find it useful to be able to parse the file without throwing errors since it's becoming more popular each day.

JSX formatting should be handled by plugins (eg. [esformatter-jsx](https://github.com/royriojas/esformatter-jsx))

**Comment by millermedeiros** [comment]
just to make it clear:

I don't think we should format JSX inside esformatter itself because: it will increase complexity; it's not part of ECMAScript; most people don't need it; can be easily implemented as a plugin;

I think esformatter should be able to parse JSX files because: it's becoming popular; espree supports it; `rocambole-jsx` doesn't work properly if mixed with plugins that removes comments and/or plugins that rely on `stringAfter` and aren't able to parse JSX.
