### ISSUE TITLE
support for trailing commas

### ISSUE THREAD

**Issue by nickdesaulniers** [millermedeiros/esformatter#274]
One thing I like to do is have trailing commas in object literals.

```js
var a = {
  b: 42,
};
```

That way, if someone later adds a new member to `a`, they don't modify the `git blame` of the line `b: 42`.

Maybe this would be a good plugin?

**Comment by millermedeiros** [comment]
uhm, this input will produce the exact same output on v0.5.0 - what are you currently experiencing?

**Comment by nickdesaulniers** [comment]
Input:
```js
var a = {
  b: 42
};
```
Output:
```js
var a = {
  b: 42,
};
```

**Comment by millermedeiros** [comment]
ahh, I think I understood what you want: **automatically add trailing commas to objects** - this would be a good plugin candidate!

**Comment by millermedeiros** [comment]
just saw this plugin that does the opposite of what you want: https://www.npmjs.com/package/esformatter-remove-trailing-commas

**Comment by Nate-Wilkins** [comment]
@millermedeiros Don't you think the plugin should do both 'add' and 'remove'? I'm only bringing this up due to my endeavors into an eslint option transformer. If the plugin were to do that and that alone I'm unable to __just__ set options for that plugin to switch from adding/removing and end up wrapping it in some weird plugin wrapper.

**Comment by kewah** [comment]
@Nate-Wilkins I chose to do `esformatter-remove-trailing-commas` instead of a plugin that handle different cases because, imho, it's better to reduce the config in the user land. Especially for things like trailing commas. If someone needs to add trailing commas then he installs `esformatter-add-trailing-commas`.

But if we need a plugin that handle both cases for an eslint option transformer, I'm open to create one and deprecate `esformatter-remove-trailing-commas`.

**Comment by millermedeiros** [comment]
@Nate-Wilkins and @kewah I like the idea of having plugins that do only one thing. It's simpler to implement and test. Too many configuration options is an anti-pattern :stuck_out_tongue_winking_eye:

But my goal is really to have some "presets" (implemented as plugins) and the user config file would load a single plugin that contains everything he needs:

```js
{
  "root": true,
  "plugins": [ "esformatter-jquery" ]
}
```

I added all the granular control because style guides can be pretty crazy and I wanted to support as many styles as possible.

**Comment by Nate-Wilkins** [comment]
@kewah I can work on an `esformatter-add-trailing-commas` if you'd like :+1: granted it'd be my first esformatter plugin. I'd definately start with the `esformatter-remove-trailing-commas` though for a reference. 

@millermedeiros Sounds like a plan!

**Comment by ckknight** [comment]
https://github.com/deoxxa/esformatter-add-trailing-commas

**Comment by millermedeiros** [comment]
thanks @ckknight and @deoxxa! closing this.
