### ISSUE TITLE
support shebang without external plugins

### ISSUE THREAD

**Issue by millermedeiros** [millermedeiros/esformatter#284]
there is https://www.npmjs.com/package/esformatter-shebang-ignore plugin but I think we should do this by default inside esformatter itself.

[grunt-esformatter](https://github.com/jzaefferer/grunt-esformatter) and [standard-format](https://github.com/maxogden/standard-format/) ended up implementing their own RegExp logic to do this..

/cc @royriojas @jzaefferer

**Comment by royriojas** [comment]
I agree. It would be nice to not require a plugin for that.

**Comment by jzaefferer** [comment]
Pulling this up into esformatter sounds good to me. Seems to be common enough.

**Comment by millermedeiros** [comment]
tricky question, should the *shebang* be removed before `pipe.before` and re-inserted after `pipe.after`?

**drawback:** if we do it that way no piped tools will be able to modify the *shebang*.
**advantage:** these tools don't need special logic to handle it (for them it will be like the file never contained a *shebang*)

PS: I don't want to add a comment like the `esformatter-shebang-ignore` because some plugin might end up removing comments and/or doing some other weird thing.

**Comment by royriojas** [comment]
Maybe I'm wrong but I was under the impression that the AST parser should be modified to properly understand the shebang. Maybe I'm wrong. I don't remember why I choose to put a comment instead of actually removing the shebang, but would removing affect the generation of a source map? or the source map is aware of the removed line? 

Should piped tools/plugins modify the shebang? is there any use case for that? If not, removing it should be pretty safe. just my 2 cents.

**Comment by jzaefferer** [comment]
> but would removing affect the generation of a source map? or the source map is aware of the removed line?

Considering sourcemaps are consumed by browers (right?), and shebang is consumed by unix binaries (right?), I don't see an issue there.

If that's correct, #289 looks good to me.

**Comment by jzaefferer** [comment]
Looks like 0.6.0 is ready \o/
