### ISSUE TITLE
support file globs?

### ISSUE THREAD

**Issue by millermedeiros** [millermedeiros/esformatter#291]
I built esformatter thinking about formatting a single file (was thinking mainly about text editors) but there seems to be a lot of people wanting to reformat whole repositories at once:

 - https://github.com/royriojas/esbeautifier
 - https://github.com/maxogden/standard-format
 - https://github.com/jzaefferer/grunt-esformatter

thinking of something like:

```sh
# multiple globs accepted (we already accept multiple files anyway)
esformatter -i lib/**.js bin/*
```

could be easily implemented by adding [node-glob](https://github.com/isaacs/node-glob) as a dependency

**Comment by jzaefferer** [comment]
Sounds good to me. esbeautifier also has a "check only" mode and more. The cache sounds interesting for my grunt plugin.

**Comment by millermedeiros** [comment]
let's rip off all the good ideas from @royriojas and standard-format :stuck_out_tongue_winking_eye:

**Comment by royriojas** [comment]
Sure, if they got into the main esformatter, I can just deprecate the other tools :D In the end the heavy lifting is done by esformatter so it might be worth to move that behavior into it.

The `check-only mode` was something I added to enforce files being beautified before being pushed to the repo and the cache was introduced because the file code base was medium size and waiting for the beautifier to finish beautifying all the files everytime was a waste of time. 

I'm all for integrate them into the main cli tool. I found myself lately moving out of the grunt/gulp world and to embrace more the npm as a build tool so I needed this that's why I didn't used the grunt wrapper over esformatter. I needed a cli version :)
