### ISSUE TITLE
indent.before.CatchKeyword = 1

### ISSUE THREAD

**Issue by Nate-Wilkins** [millermedeiros/esformatter#312]
Not sure  if this desired behavior or not but setting `lineBreak.before.CatchKeyword = 1` I'd expect the following code to be formatted with a line break before any catch keywords.

```js
try {
    somethingRisky();
} catch (e) {
    console.error(e);
}
```
Formatted: 
```js
try {
    somethingRisky();
}
catch (e) {
    console.error(e);
}
```

But instead I get the original back.

**Comment by millermedeiros** [comment]
I believe the `lineBreak.before.CatchKeyword = 1` is being overwritten by `lineBreak.after.TryClosingBrace = 0`

we have tests that show that the behavior you want is possible but we used  `lineBreak.after.TryClosingBrace = 1` instead of `CatchKeyword`: 

 - https://github.com/millermedeiros/esformatter/blob/master/test/compare/custom/try_statement-out.js
 - https://github.com/millermedeiros/esformatter/blob/master/test/compare/custom/try_statement-config.json

that happens because the formatting starts from the leaf nodes and moves until the root node. -- `CatchClause` is inside the `TryStatement`, so `TryStatement` can basically override everything from `CatchClause`.

**Comment by Nate-Wilkins** [comment]
Ah I see, I'll check those out. Thanks!
