### ISSUE TITLE
Space after comma in object expression while retaining bracket white space

### ISSUE THREAD

**Issue by Flet** [millermedeiros/esformatter#313]
I'd like to have this:
```
var x = {key: 123,more: 456}
```
turn into this
```
var x = {key: 123, more: 456}
                  ^
__________________|

```

But also keep the existing white space for the opening/closing brackets, so this would also be untouched when formatted:
```
var g = { name: f, data: fs.readFileSync(f).toString() }
```

Is there any way to force white space after the comma between properties?

**Comment by kewah** [comment]
@Flet you should take a look to https://github.com/wbinnssmith/esformatter-collapse-objects A PR is open to let/remove the whitespace after & before the braces https://github.com/wbinnssmith/esformatter-collapse-objects/issues/1

**Comment by millermedeiros** [comment]
the space **after** the comma is handled by `whiteSpace.before.Property = 1` or `whiteSpace.before.PropertyName = 1`. the space **before** the comma is handled by `whiteSpace.after.PropertyValue = 0` or `whiteSpace.after.Property = 0`  (`PropertyName` and `PropertyValue` overrides the global `Property` setting since they are more specific)

to really leave the `{}` untouched is tricky since the `after.Property(Value)` and `before.Property(Name)` will conflict with `after.ObjectExpressionOpeningBrace = -1` and `before.ObjectExpressionClosingBrace = -1`... you probably need to keep it consistent and set the value to `1`.

I'll submit a pull request to `esformatter-collapse-objects` soon with the changes required to follow the default esformatter settings.

**Comment by Flet** [comment]
Thanks @millermedeiros

I'm not exactly looking to collapse object literals, I just want a space after the commas without affecting the braces :)

**Comment by millermedeiros** [comment]
@Flet I guess that we would need a new setting (maybe `ObjectExpressionComma` to match `ArrayExpressionComma`) and set `Property`, `PropertyValue` and `PropertyName` to `-1`... but there are always ways to introduce conflicts (if last property is an Array and you have `after.ArrayExpressionClosing = 1` it won't work as you expect since `ArrayExpressionClosing` will limit the amount of spaces)

we can't deprecate the `Property[Name|Value]` because there are probably a lot of people using these settings.. If we add the `ObjectExpressionComma` I would need to submit another PR for the `esformatter-collapse-objects`...

I think we will have to live with the current logic, if you always want to have 1 space inside `{}` set it to `1`, if you always want to remove the spaces set it to `0`.

it's really hard to make a formatter that keeps the original formatting.

**Comment by millermedeiros** [comment]
going to ignore this since there isn't a clear way to solve the problem without causing conflicts.

**Comment by Flet** [comment]
Thanks, makse sense to do this.
