### ISSUE TITLE
how to ignore node_modules using the cli API?

### ISSUE THREAD

**Issue by vvo** [millermedeiros/esformatter#329]
Let's say I want to rewrite all the JavaScript files in my project BUT the node_modules, how to do that?

**Comment by vvo** [comment]
something like this:

```sh
esformatter '!(node_modules|build|dist){,/**/}*.js'
```

(rough!)

**Comment by vvo** [comment]
@millermedeiros this is not the best option since it emits an error when you do not have any subdirectory.. Maybe you have a better idea?

**Comment by vvo** [comment]
So that's because when you give a pattern to glob that results in no matches, you get back a similar pattern. Switching to non sync glob should solve the issue, but that's some work

**Comment by millermedeiros** [comment]
yes, we need a better way to do this and also to add it to the docs.

the error [I did on purpose](https://github.com/millermedeiros/esformatter/blob/98e4f27774bf425f95018f7c0419b0f0ea65d6e7/lib/cli.js#L132-L134) because I assumed it was better to display that it couldn't find any files with the glob than to fail silently.. (specially for cases like `esformatter 'wrong_path.js'`) but maybe we should change this behavior and/or add a flag to toggle it.

**Comment by millermedeiros** [comment]
I think we should probably add an `--ignore-dir` argument to the CLI.. so we can do `esformatter --ignore-dir=node_modules --ignore-dir=build --ignore-dir=dist  './**/*.js'` and maybe ignore `node_modules` by default (if we ignore it by default we should add a `--noignore-dir` argument as well)

**Comment by millermedeiros** [comment]
sorry for the huuuuuuge delay, but in the next version (v0.10.0) we will be able to specify complex ignore rules like:

```sh
esformatter --diff --ignore 'node_modules/**' --ignore 'test/compare/**/*-in.js' --ignore 'test/compare/{jquery,custom,rc,error}/**/*.js' '**/*.js'
```

I'll probably do some follow up work on #449 to support `.eslintignore`, `.gitignore`, etc...
