### ISSUE TITLE
Upgrade to latest espree

### ISSUE THREAD

**Issue by fantasy8-me** [millermedeiros/esformatter#349]
Is it possible to upgrade the espree to latest version, which supports 'ObjectRestSpread'

**Comment by millermedeiros** [comment]
`espree@2.x` breaks a few things on our unit tests, mostly because the AST structure changed between v1 and v2 (to follow the [estree project](https://github.com/estree/estree/)).

Fixing the errors should not be that hard - mostly need to update the way we handle `ParameterDefault` inside `hooks/Params`, and a few errors on the try/catch hooks.

pull requests are highly appreciated!
