### ISSUE TITLE
Failing to parse .bind() on arrow function

### ISSUE THREAD

**Issue by gavocanov** [millermedeiros/esformatter#361]
Hi,

It seems like EsFormatter is having problems parsing this code example:

```javascript
'use strict';

const test = {
    a: 0,

    b: () => {   
        setInterval(() => {
            console.log(this.a++);
        }.bind(this), 1000);
    }
}

test.b();
```
The error is:
`Error: test.js:9 Unexpected token .`
It's failing to understand the }.bind token.

It seems to work ok for normal functions, ie. this code:
```javascript
'use strict';

const test = {
    a: 0,

    b: function() {
        setInterval(function() {
            console.log(this.a++);
        }.bind(this), 1000);
    }
}

test.b();
``` 
is parsed correctly.

Thnx in advance, and thank you very much for esformatter!!

**Comment by millermedeiros** [comment]
the whole point of arrow functions is to not need to `bind` the context (arrow functions are automatically bound to `this`).

arrow functions don't have access to the `arguments` object and you can't actually change the `this` value dynamically:

 > Because `this` is lexically bound, `arrow.call` and `arrow.apply` cannot bind a different `this` parameter value, but they can pass arbitrary arguments, of course.
 > http://tc39wiki.calculist.org/es6/arrow-functions/

the first example won't run as expected; if it was a regular function calling `test.b()` it was supposed to change the `this` value to be the `test` object, but the arrow function uses the *lexical `this`* — value of `this` during the creation of the arrow function.. — this should work as expected tho:

```js
const test = {
    a: 0,

    b: function() {
        setInterval(() => {
            console.log(this.a++);
        }, 1000);
    }
}

test.b();
```

given that `bind` is unnecessary, firefox also throws an error for your first example (because of `.bind`), and the parsing is done by [espree](https://github.com/eslint/espree), not esformatter itself; I'm marking it as invalid.

cheers.

**Comment by gavocanov** [comment]
This works in Node and since there is no lexical this in node (with --harmony) yet (0.12.x) I have to use .bind(this), don't know if this is implemented in io.js or node v4.0 tho.

But anyway, makes sense to conform to standards not (half) implementations.
Thnx for the quick reply and info.
