### ISSUE TITLE
Custom Parser

### ISSUE THREAD

**Issue by jwhitmarsh** [millermedeiros/esformatter#397]
Since the API allows you to change the parser, could it not be an option in the config? It'd be great to be able to use the babel-parser.

**Comment by millermedeiros** [comment]
babel-parser is not so simple to use (requires some extra options to make it work). I'm going to probably release a new version soon that uses the babel parser by default since it contains more options.

I already have a working branch, only problem is that it is a little bit slower than current implementation since it requires https://github.com/babel/acorn-to-esprima

**Comment by jwhitmarsh** [comment]
Awesome, that sounds promising - thanks :)

**Comment by millermedeiros** [comment]
FYI, v0.9.0 uses babel by default. Will keep this issue open since other users might need different parsers.. - should not be hard to implement, but I'll mark it as low-priority since Babel supports most features.

**Comment by ariya** [comment]
JFYI, Babel's parser (Babylon) starts to deviate from ESTree. This may or may not be problem (when working with other ESTree-based tools).

**Comment by millermedeiros** [comment]
I'm going to close this for now since [babylon + acorn-to-esprima](https://github.com/millermedeiros/esformatter-parser) should be fine for most cases and it would increase complexity... but feel free to comment in case this is still useful for someone (explaining why).
