### ISSUE TITLE
Line breaks not affecting ImportSpecifier nodes in ES2015

### ISSUE THREAD

**Issue by venoma333** [millermedeiros/esformatter#402]
The problem is that esformatter is unable to deal with code like this:
`import { searchCitiesByName, hideResults, showResults, navigateResults, deselectResults } from '../actions/search';`

This is my .esformatterrc:
```
{
  "plugins": ["esformatter-jsx"],
  "lineBreak": {
    "before": {
      "ImportSpecifier": 2
    },
    "after": {
      "ImportSpecifier": 2
    }
  },
  "indent": {
    "value": "  "
  },
  "jsx": {
    "formatJSX": true,
    "attrsOnSameLineAsTag": false,
    "maxAttrsOnTag": 1,
    "firstAttributeOnSameLine": true,
    "spaceInJSXExpressionContainers": "",
    "alignWithFirstAttribute": false,
    "htmlOptions": {
      "brace_style": "collapse",
      "indent_char": " ",
      "indent_size": 2,
      "max_preserve_newlines": 2,
      "preserve_newlines": true
    }
  }
}
```

I should also mention that I am using it with the Atom [esformatter](https://github.com/sindresorhus/atom-esformatter) package.

**Comment by millermedeiros** [comment]
we have some tests for import/export: see [input](https://github.com/millermedeiros/esformatter/blob/master/test/compare/default/module-in.js) and [output](https://github.com/millermedeiros/esformatter/blob/master/test/compare/default/module-out.js)

what is the problem that you're experiencing? do you get an error, or is it not formatted the way you'd expect? can you provide the input and expected output?

this logic is handled by https://github.com/millermedeiros/esformatter/blob/master/lib/hooks/ImportSpecifier.js

**Comment by millermedeiros** [comment]
I think I get what you're trying to do.

input:

```js
import {foo, bar,baz} from 'ipsum';
```

expected output:

```js
import {
  foo,
  bar,
  baz
} from 'ipsum';
```

and this will indeed fail with the settings you provided.

the logic that adds the line breaks around the "node" actually happens [before the hook transform call](https://github.com/millermedeiros/esformatter/blob/cf7ddf19eae393df791052c8024e769fc66123ca/lib/transform.js#L61) and it only really works for [some very specific cases](https://github.com/millermedeiros/esformatter/blob/cf7ddf19eae393df791052c8024e769fc66123ca/lib/lineBreakAroundNode.js#L61-L101)... I did not try to debug this yet, but the `_br.limit` calls inside the [ImportSpecifier hook](https://github.com/millermedeiros/esformatter/blob/master/lib/hooks/ImportSpecifier.js) would actually override this setting even if it passed the `shouldLimitLineBreakAroundNode` test...

we will probably need to add some extra settings to limit spaces and line breaks around `{` and `}` and `,` instead of simply calling `_br.limit(braceStart, 0)`.

pull requests are highly appreciated, I won't have time to work on esformatter this week.

**Comment by sarman** [comment]
+1
