### ISSUE TITLE
Formatting rule & plugin order

### ISSUE THREAD

**Issue by jmullo** [millermedeiros/esformatter#415]
It should be possible to configure the order in which plugins are executed.
It should also be possible to configure whether plugins are executed before or after default rules.

Currently if I have "esformatter-use-strict" plugin and "esformatter-quotes" plugin configured to use double quotes, I end up with "use strict" having single quotes in the resulting formatted code.

**Comment by millermedeiros** [comment]
the order that plugins are listed in the array should affect the order they are executed, but some plugins use `stringBefore`, while others work with `tokenBefore` or `nodeAfter`.. and that changes the order that they end up being executed:

 > The plugin methods are executed in the following order: `setOptions` > `stringBefore` > `transformBefore` > `tokenBefore` > `nodeBefore` > `nodeAfter` > `tokenAfter` > `transformAfter` > `stringAfter`. [plugins.md](https://github.com/millermedeiros/esformatter/blob/master/doc/plugins.md)

maybe I should update `esformatter-quotes` to use `tokenAfter` instead..

everything is applied in a single pass/loop to improve performance, otherwise every single plugin would require a full loop and there would be no way for us to add something like `nodeBefore` and `nodeAfter`...

**Comment by twolfson** [comment]
It seems reasonable but a bit of a hack. Maybe we should shift the responsibility of what gets grouped into a single pass to the user?

For example:

```json
plugins: [
  // Group these 2 into single pass
  ['esformatter-quotes', 'esformatter-var-each'],
  // Run as its own pass after the others
  'esformatter-use-strict'
  // Alternative synax: `['esformatter-use-strict']`
],
// Flag to enable new behavior so we can preserve backwards compatibility
//   and performance for default behavior
multiplePasses: true
```

**Comment by millermedeiros** [comment]
I was planning to implement something similar to what @twolfson suggested but I'm thinking that we should keep the current behavior for now. There are plugins like [esformatter-jsx](https://github.com/royriojas/esformatter-jsx) that removes some nodes during `stringBefore` and restore them during `stringAfter`... If we allow multiple passes, they would never be able to implement the `formatJSXExpressions: false` feature.

The `esformatter-use-strict` plugin should be using `stringBefore` instead of `stringAfter`, that way the quotes would be formatter properly. (Or it should be changed to accept the same config as `esformatter-quotes`)

Sorry, but I'm going to close it as wontfix for now.
